language: java
# Режим обычного пользователя для сборки проекта
sudo: false

script: "mvn cobertura:cobertura"

# После выполнения сборки запустить скрипт, который будет собирать статистику по Jacoco
# Используется сервис https://codecov.io/bash
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправка уведомпения на почту
notifications:
  email:
    recipients:
      - andreyzarazka@gmail.com
    on_success: never
    on_failure: always